name: firebase_practicing
description: Firebase Project for  Practicing

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1
environment:
  sdk: ">=2.16.1 <3.0.0"



dependencies:
  string_extensions: ^0.4.1
  pin_code_fields: ^7.3.0
  carousel_slider: ^4.0.0
  liquid_progress_indicator: ^0.4.0
  fluttertoast: ^8.0.9
  smooth_page_indicator: ^1.0.0+2
  shared_preferences: ^2.0.13

  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  conditional_builder_null_safety: ^0.0.6
  hexcolor: ^2.0.6
  material_design_icons_flutter: ^5.0.6595
  dio: ^4.0.4
  http: ^0.13.4
  firebase_core: ^1.13.1
  firebase_database: ^9.0.8
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  firebase_auth: ^3.3.11
  cloud_firestore: ^3.1.10
  firebase_storage: ^10.2.9
  image_picker: ^0.8.4+11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Jannah
      fonts:
        - asset: assets/fonts/jannah.ttf
          weight: 700
    - family: IconBroken
      fonts:
        - asset: assets/fonts/icons.ttf