// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDgVecw1NKHajnjDf3A1YmUtZXnILWBFI',
    appId: '1:941087024472:android:471a4d20a7ec7c61a2712d',
    messagingSenderId: '941087024472',
    projectId: 'fir-for-practicing',
    databaseURL: 'https://fir-for-practicing-default-rtdb.firebaseio.com',
    storageBucket: 'fir-for-practicing.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhcZdqMNMkzFZ0x2iyJdA4rBnRZMc45Xc',
    appId: '1:941087024472:ios:54424ccd7d0750bfa2712d',
    messagingSenderId: '941087024472',
    projectId: 'fir-for-practicing',
    databaseURL: 'https://fir-for-practicing-default-rtdb.firebaseio.com',
    storageBucket: 'fir-for-practicing.appspot.com',
    androidClientId: '941087024472-ss37blc408r2hfebv0vchkngog03804u.apps.googleusercontent.com',
    iosClientId: '941087024472-14kbod1n17ejrnfits90hnlcphr0ivtl.apps.googleusercontent.com',
    iosBundleId: 'no',
  );
}
